Hw 32: створив кастомну модель користувача та реалізував для неї реєстрацію (створення), логін та логаут. Signup/signin реалізував через forms.py.
VolodymyrKhabarov/blog_django pull request #3
Opened 2023-02-11 19:44 UTC by VolodymyrKhabarov

FYI: @shorodilov,

## Description

створив кастомну модель користувача та реалізував для неї реєстрацію (створення), логін та логаут. Signup/signin реалізував через forms.py.

## Checklist before requesting a review

- [+] I have performed a self-review of my code
- [+] I have check it is running in the development environment

2023-02-13 12:57 UTC, shorodilov requested changes
Загалом файно.
Треба трохи виправити `signin/signup_view`

2023-02-13 12:57 UTC, shorodilov commented on users/models.py
> +        db_table = "users"
Зазвичай використовують імена таблиць в однині:
`post`, `user`, `product`, `order` etc.

Не помилка, просто для інформації

2023-02-13 12:57 UTC, shorodilov commented on users/views.py
> +        form = SignInForm()
у тебе по факту, ці ж рядки ідуть далі.
залиш обробку запиту:
```python
if request.method == "POST":
    form = SignInForm(request.POST)  # форма з даними
    if form.is_valid():
        ...
if request.method == "GET":
    form = SignInForm()  # створити порожню форму
# якщо форма невілдна - передаємо заповнену форму
# якщо запит GET - порожню форму
return render(..., {"form": form}
```

2023-02-13 12:57 UTC, shorodilov commented on users/views.py
> +        redirect_url = reverse_lazy("signup")
Аналогічно до `signin_view`

2023-02-14 12:52 UTC, VolodymyrKhabarov commented
@shorodilov виправив згідно пропозицій: signup та signin views; назву таблиці users на user у моделі UserModel застосунку users

2023-02-14 18:47 UTC, shorodilov approved these changes
lgtm

2023-02-14 18:47 UTC, shorodilov commented on users/forms.py
> +class SignUpForm(UserCreationForm):
От тут дуже не звичайний мікс `Form`та `ModelForm`. Багато полів вже визначено в `UserCreationForm`. Тобто робиш забагато зайвої праці.

2023-02-14 18:47 UTC, shorodilov commented on users/forms.py
> +class SignInForm(AuthenticationForm):
У тебе клас по факту лише для CSS

2023-02-14 19:14 UTC, merged